import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const STRATA_EXPERIMENTAL = truthy("STRATA_EXPERIMENTAL")
const STRATA_DISABLE_CLAUDE_CODE = truthy("STRATA_DISABLE_CLAUDE_CODE")
const STRATA_DISABLE_CLAUDE_CODE_SKILLS =
  STRATA_DISABLE_CLAUDE_CODE || truthy("STRATA_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["STRATA_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  STRATA_AUTO_SHARE: truthy("STRATA_AUTO_SHARE"),
  STRATA_AUTO_HEAP_SNAPSHOT: truthy("STRATA_AUTO_HEAP_SNAPSHOT"),
  STRATA_GIT_BASH_PATH: process.env["STRATA_GIT_BASH_PATH"],
  STRATA_CONFIG: process.env["STRATA_CONFIG"],
  STRATA_CONFIG_CONTENT: process.env["STRATA_CONFIG_CONTENT"],
  STRATA_DISABLE_AUTOUPDATE: truthy("STRATA_DISABLE_AUTOUPDATE"),
  STRATA_ALWAYS_NOTIFY_UPDATE: truthy("STRATA_ALWAYS_NOTIFY_UPDATE"),
  STRATA_DISABLE_PRUNE: truthy("STRATA_DISABLE_PRUNE"),
  STRATA_DISABLE_TERMINAL_TITLE: truthy("STRATA_DISABLE_TERMINAL_TITLE"),
  STRATA_SHOW_TTFD: truthy("STRATA_SHOW_TTFD"),
  STRATA_PERMISSION: process.env["STRATA_PERMISSION"],
  STRATA_DISABLE_DEFAULT_PLUGINS: truthy("STRATA_DISABLE_DEFAULT_PLUGINS"),
  STRATA_DISABLE_LSP_DOWNLOAD: truthy("STRATA_DISABLE_LSP_DOWNLOAD"),
  STRATA_ENABLE_EXPERIMENTAL_MODELS: truthy("STRATA_ENABLE_EXPERIMENTAL_MODELS"),
  STRATA_DISABLE_AUTOCOMPACT: truthy("STRATA_DISABLE_AUTOCOMPACT"),
  STRATA_DISABLE_MODELS_FETCH: truthy("STRATA_DISABLE_MODELS_FETCH"),
  STRATA_DISABLE_MOUSE: truthy("STRATA_DISABLE_MOUSE"),
  STRATA_DISABLE_CLAUDE_CODE,
  STRATA_DISABLE_CLAUDE_CODE_PROMPT: STRATA_DISABLE_CLAUDE_CODE || truthy("STRATA_DISABLE_CLAUDE_CODE_PROMPT"),
  STRATA_DISABLE_CLAUDE_CODE_SKILLS,
  STRATA_DISABLE_EXTERNAL_SKILLS: STRATA_DISABLE_CLAUDE_CODE_SKILLS || truthy("STRATA_DISABLE_EXTERNAL_SKILLS"),
  STRATA_FAKE_VCS: process.env["STRATA_FAKE_VCS"],
  STRATA_SERVER_PASSWORD: process.env["STRATA_SERVER_PASSWORD"],
  STRATA_SERVER_USERNAME: process.env["STRATA_SERVER_USERNAME"],
  STRATA_ENABLE_QUESTION_TOOL: truthy("STRATA_ENABLE_QUESTION_TOOL"),

  // Experimental
  STRATA_EXPERIMENTAL,
  STRATA_EXPERIMENTAL_FILEWATCHER: Config.boolean("STRATA_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  STRATA_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("STRATA_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  STRATA_EXPERIMENTAL_ICON_DISCOVERY: STRATA_EXPERIMENTAL || truthy("STRATA_EXPERIMENTAL_ICON_DISCOVERY"),
  STRATA_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("STRATA_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  STRATA_ENABLE_EXA: truthy("STRATA_ENABLE_EXA") || STRATA_EXPERIMENTAL || truthy("STRATA_EXPERIMENTAL_EXA"),
  STRATA_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("STRATA_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  STRATA_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("STRATA_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  STRATA_EXPERIMENTAL_OXFMT: STRATA_EXPERIMENTAL || truthy("STRATA_EXPERIMENTAL_OXFMT"),
  STRATA_EXPERIMENTAL_LSP_TY: truthy("STRATA_EXPERIMENTAL_LSP_TY"),
  STRATA_EXPERIMENTAL_LSP_TOOL: STRATA_EXPERIMENTAL || truthy("STRATA_EXPERIMENTAL_LSP_TOOL"),
  STRATA_EXPERIMENTAL_PLAN_MODE: STRATA_EXPERIMENTAL || truthy("STRATA_EXPERIMENTAL_PLAN_MODE"),
  STRATA_EXPERIMENTAL_MARKDOWN: !falsy("STRATA_EXPERIMENTAL_MARKDOWN"),
  STRATA_MODELS_URL: process.env["STRATA_MODELS_URL"],
  STRATA_MODELS_PATH: process.env["STRATA_MODELS_PATH"],
  STRATA_DISABLE_EMBEDDED_WEB_UI: truthy("STRATA_DISABLE_EMBEDDED_WEB_UI"),
  STRATA_DB: process.env["STRATA_DB"],
  STRATA_DISABLE_CHANNEL_DB: truthy("STRATA_DISABLE_CHANNEL_DB"),
  STRATA_SKIP_MIGRATIONS: truthy("STRATA_SKIP_MIGRATIONS"),
  STRATA_STRICT_CONFIG_DEPS: truthy("STRATA_STRICT_CONFIG_DEPS"),

  STRATA_WORKSPACE_ID: process.env["STRATA_WORKSPACE_ID"],
  STRATA_EXPERIMENTAL_HTTPAPI: truthy("STRATA_EXPERIMENTAL_HTTPAPI"),
  STRATA_EXPERIMENTAL_WORKSPACES: STRATA_EXPERIMENTAL || truthy("STRATA_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get STRATA_DISABLE_PROJECT_CONFIG() {
    return truthy("STRATA_DISABLE_PROJECT_CONFIG")
  },
  get STRATA_TUI_CONFIG() {
    return process.env["STRATA_TUI_CONFIG"]
  },
  get STRATA_CONFIG_DIR() {
    return process.env["STRATA_CONFIG_DIR"]
  },
  get STRATA_PURE() {
    return truthy("STRATA_PURE")
  },
  get STRATA_PLUGIN_META_FILE() {
    return process.env["STRATA_PLUGIN_META_FILE"]
  },
  get STRATA_CLIENT() {
    return process.env["STRATA_CLIENT"] ?? "cli"
  },
  // stratacode_change start
  get STRATA_SESSION_RETRY_LIMIT() {
    return number("STRATA_SESSION_RETRY_LIMIT")
  },
  // stratacode_change end
}
